name: Build common setup

inputs:
  contribsys-credentials:
    description: "Contribsys credentials"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - run: pnpm i
      shell: bash

    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMS__CONTRIBSYS__COM: ${{ inputs.contribsys-credentials }}
      with:
        working-directory: apps/rails
        bundler-cache: true # runs "bundle install" and caches installed gems automatically
