name: Rspec CI
on: push

# Cancel builds for previous commits on the same branch unless the branch is "main"
concurrency:
  group: ${{ github.ref }}-rspec
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
  GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
  GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  QUICKBOOKS_CLIENT_ID: ${{ secrets.QUICKBOOKS_CLIENT_ID }}
  QUICKBOOKS_CLIENT_SECRET: ${{ secrets.QUICKBOOKS_CLIENT_SECRET }}
  QUICKBOOKS_WEBHOOK_SECRET: ${{ secrets.QUICKBOOKS_WEBHOOK_SECRET }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  CLEARBIT__API_KEY: ${{ secrets.CLEARBIT__API_KEY }}
  HELPER__SECRET_KEY: ${{ secrets.HELPER__SECRET_KEY }}
  HELPER__WIDGET_KEY: ${{ secrets.HELPER__WIDGET_KEY }}
  IRS__CLIENT_ID: ${{ secrets.IRS__CLIENT_ID }}
  IRS__TCC_1042: ${{ secrets.IRS__TCC_1042 }}
  IRS__TCC_1099: ${{ secrets.IRS__TCC_1099 }}
  IRS__USER_ID: ${{ secrets.IRS__USER_ID }}
  RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
  WISE_GUMROAD_ACCOUNT__ABARTN: ${{ secrets.WISE_GUMROAD_ACCOUNT__ABARTN }}
  WISE_GUMROAD_ACCOUNT__ACCOUNT_NUMBER: ${{ secrets.WISE_GUMROAD_ACCOUNT__ACCOUNT_NUMBER }}
  HELPER_WIDGET_HOST: ${{ secrets.HELPER_WIDGET_HOST }}
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
  WISE_API_KEY: ${{ secrets.WISE_API_KEY }}
  WISE_PROFILE_ID: ${{ secrets.WISE_PROFILE_ID }}
  DOCUSEAL_TOKEN: ${{ secrets.DOCUSEAL_TOKEN }}
  DOCUSEAL_USER_EMAIL: ${{ secrets.DOCUSEAL_USER_EMAIL }}
  ACTIVERECORD_DETERMINISTIC_DERIVED_KEY: ${{ secrets.ACTIVERECORD_DETERMINISTIC_DERIVED_KEY }}
  ACTIVERECORD_DERIVED_KEY: ${{ secrets.ACTIVERECORD_DERIVED_KEY }}

jobs:
  rspec:
    name: Tests
    runs-on: ubicloud-standard-2

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: flexile_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6.2.3
        ports:
          - 6389:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]

    steps:
      - uses: actions/checkout@v4

      - name: Build setup
        uses: ./.github/common/
        with:
          contribsys-credentials: ${{ secrets.SIDEKIQ_PRO_KEY }}

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: cd apps/rails && bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.SIDEKIQ_PRO_KEY }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          RUBY_YJIT_ENABLE: 1
          KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_LOG_LEVEL: info
          SIDEKIQ_REDIS_URL: ${{ secrets.SIDEKIQ_REDIS_URL }}
        run: cd apps/rails && bundle exec rake "knapsack_pro:queue:rspec[--format RSpec::Github::Formatter --tag ~skip --tag ~type:system --format progress]"
        timeout-minutes: 20
