name: Playwright CI
on: push

# Cancel builds for previous commits on the same branch unless the branch is "main"
concurrency:
  group: ${{ github.ref }}-playwright
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  RUBY_YJIT_ENABLE: 1
  KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}
  KNAPSACK_PRO_LOG_LEVEL: info
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
  GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
  GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  QUICKBOOKS_CLIENT_ID: ${{ secrets.QUICKBOOKS_CLIENT_ID }}
  QUICKBOOKS_CLIENT_SECRET: ${{ secrets.QUICKBOOKS_CLIENT_SECRET }}
  QUICKBOOKS_WEBHOOK_SECRET: ${{ secrets.QUICKBOOKS_WEBHOOK_SECRET }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  CLEARBIT__API_KEY: ${{ secrets.CLEARBIT__API_KEY }}
  HELPER__SECRET_KEY: ${{ secrets.HELPER__SECRET_KEY }}
  HELPER__WIDGET_KEY: ${{ secrets.HELPER__WIDGET_KEY }}
  IRS__CLIENT_ID: ${{ secrets.IRS__CLIENT_ID }}
  IRS__TCC_1042: ${{ secrets.IRS__TCC_1042 }}
  IRS__TCC_1099: ${{ secrets.IRS__TCC_1099 }}
  IRS__USER_ID: ${{ secrets.IRS__USER_ID }}
  RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
  WISE_GUMROAD_ACCOUNT__ABARTN: ${{ secrets.WISE_GUMROAD_ACCOUNT__ABARTN }}
  WISE_GUMROAD_ACCOUNT__ACCOUNT_NUMBER: ${{ secrets.WISE_GUMROAD_ACCOUNT__ACCOUNT_NUMBER }}
  HELPER_WIDGET_HOST: ${{ secrets.HELPER_WIDGET_HOST }}
  WISE_API_KEY: ${{ secrets.WISE_API_KEY }}
  WISE_PROFILE_ID: ${{ secrets.WISE_PROFILE_ID }}
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
  ACTIVERECORD_DETERMINISTIC_DERIVED_KEY: ${{ secrets.ACTIVERECORD_DETERMINISTIC_DERIVED_KEY }}
  ACTIVERECORD_DERIVED_KEY: ${{ secrets.ACTIVERECORD_DERIVED_KEY }}

jobs:
  playwright:
    name: Tests (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubicloud-standard-2
    strategy:
      fail-fast: false
      matrix:
        shardTotal: [5]
        shardIndex: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4

      - name: Build setup
        uses: ./.github/common/
        with:
          contribsys-credentials: ${{ secrets.SIDEKIQ_PRO_KEY }}

      - run: node docker/createCertificate.js

      - name: Run docker compose
        run: docker compose -f docker/docker-compose-local-linux.yml up -d

      - run: pnpm vercel link --scope anti-work --yes --token ${{ secrets.VERCEL_ENV_KEY }} && pnpm vercel env pull .env --token ${{ secrets.VERCEL_ENV_KEY }} && ln -s $PWD/.env ./apps/next/.env

      - run: NODE_ENV=test pnpm run build-next --no-lint
        shell: bash

      - name: Install foreman
        run: gem install foreman

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Update .env.test with encryption keys
        run: |
          echo "ACTIVERECORD_DETERMINISTIC_DERIVED_KEY=${{ secrets.ACTIVERECORD_DETERMINISTIC_DERIVED_KEY }}" >> .env.test
          echo "ACTIVERECORD_DERIVED_KEY=${{ secrets.ACTIVERECORD_DERIVED_KEY }}" >> .env.test

      - name: Run Playwright tests
        run: pnpm playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 7
